# .pre-commit-config.yaml

# Hooks génériques (trim, EOF, etc.) — version PINNÉE
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict

  # Hooks locaux qui invoquent directement cargo & outils CLI
  - repo: local
    hooks:
      # format (rapide) -> à chaque commit
      - id: cargo-fmt
        name: cargo fmt --check
        entry: bash -lc 'cargo fmt --all -- --check'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      # lint (peut être un peu plus long) -> à chaque commit
      - id: cargo-clippy
        name: cargo clippy -D warnings
        entry: bash -lc 'cargo clippy --workspace --all-targets --all-features -- -D warnings'
        language: system
        pass_filenames: false
        stages: [pre-commit]

      # sécurité & policy — plus lents -> au **push** seulement
      - id: cargo-deny
        name: cargo deny check licenses
        entry: bash -lc 'cargo deny check licenses'
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: cargo-audit
        name: cargo audit
        entry: bash -lc 'cargo audit'
        language: system
        pass_filenames: false
        stages: [pre-push]
