[package]
name = "lib_n2kparser"
authors = ["fulup@iot.bzh"]
version = "0.1.0"
#edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json={ version= "1.0" }
lib_sockcan= {path ="../sockcan"}

[[bin]]
name = "can-n2k"
path = "src/json-parser.rs"
